### PR TITLE
Add check if certain metaData is already set

### PR DESCRIPTION
**Pull request by coolcat-creations**
If any metaData is already set by Template or somewhere else i added checks to see if it´s already set.
In my test it works, please give advice if there is something wrong done.

### CODE REVIEW

**Comment by mbabker** [comment]
In theory this is right but the way we've structured this for the .org
sites it's intended for this plugin to always set the metadata then the
template to only set it if it isn't already set elsewhere.  So it sounds
like whatever site you're trying to use this with has another plugin or a
component setting metadata separately.

**Comment by coolcat-creations** [comment]
Ok great, thanks! So this workaround is ok but doesn´t match the J! Property workflow, right?

**Comment by mbabker** [comment]
Well it doesn't match the intent.  Considering this still only works with
com_content the only way you get this conflict is if you've got another
plugin setting this same data or are using sh404.  If you tweak the plugin
ordering you could get around that.

**Comment by coolcat-creations** [comment]
I setup some parameters in a (non J! Property) Template for Social Media Meta Tags and want to use them as general and then the metas were set double. I have the possibility to disable some or all of the parameters in the template by so in this case the plugin would take over. Please don´t think that i use sh404 :-D

**Comment by mbabker** [comment]
Ahh.  Well, while its a valid use case, it's not necessarily in line with
how we've structured this for use on the J! Properties.  Let me think this
one over, since the plugin's main consumer is joomla.org I'm not too keen
on adding too many "features" beyond the use case there.

**Comment by coolcat-creations** [comment]
Yes, i understand thanks!

**Comment by mbabker** [comment]
It's not causing any harm and improves compatibility with other stuff I guess.  Merged.

**Comment by coolcat-creations** [comment]
thanks! :-)

**Pull request merged**
