### PR TITLE
Removed script.php from xml file

### PR DESCRIPTION
**Pull request by yvesh**

### CODE REVIEW

**Comment by mbabker** [comment]
Actually, I'm going to decline this PR.  I'm going to do some updates on the metadata uses to work more efficiently with the JDocument changes added in Joomla 3.6 and I'll add a script file to restrict new version installs to 3.6, so this will actually start to be used when I do the updates.

**Comment by piotr-cz** [comment]
Then in this repo readme's should be a note about minimal requirement of Joomla 3.6.
Joomla installations with lower version don't have the `JInstallerScript` and thus installation fails.

**Comment by mbabker** [comment]
I skimped out on docs because this is mainly built for the .org sites.  That can go onto the mile long TODO list.

**Comment by piotr-cz** [comment]
I understand, but this is best extension for social sites metadata on github

**Comment by piotr-cz** [comment]
@mbabker Thanks for updating README in 37df446db468c248bdce7c38fc221b4589501e09

**Pull request closed without merging**
