### PR TITLE
Add ogimage width and height

### PR DESCRIPTION
**Pull request by zero-24**
@coolcat-creations please confirm that this is what you had in mind here: https://github.com/joomla-projects/plg_content_joomlarrssb/issues/14

https://www.php.net/manual/en/function.getimagesize.php
https://ogp.me/#structured

### CODE REVIEW

**Comment by zero-24** [comment]
Would it make sense to add the mime type too?

og:image:type ? @coolcat-creations @conconnl ?

**Comment by zero-24** [comment]
Here is a demo package that includes the changes of this PR for you to test @coolcat-creations 

[plg_content_joomlarrssb.zip](https://github.com/joomla-projects/plg_content_joomlarrssb/files/5133815/plg_content_joomlarrssb.zip)

**Comment by zero-24** [comment]
Also the latest commit is already included in the package and deployed.

**Comment by conconnl** [comment]
I have checked the output on one of our test sites.

This is the image in the article:
image (1)

This was the output for that page:
image

As we can conclude the OG Metadata shows the correct image size and image type.

**Comment by zero-24** [comment]
Thanks @conconnl merging now.

**Pull request merged**
